language: node_js
node_js:
  - "8.11.1"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm i --no-save codecov

script:
  - npm run lib:test
  - npm run lib:build

after_success:
  - npm run codecov
